name: CI/CD Workflow

env:
  ACTIONS_STEP_DEBUG: true


on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: |
          echo "No tests yet"

  deploy-to-heroku:
    name: Deploy to Heroku
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh

      - name: Log in to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          echo "machine api.heroku.com
          login ${{ secrets.HEROKU_EMAIL }}
          password ${{ secrets.HEROKU_API_KEY }}" > ~/.netrc
          chmod 600 ~/.netrc

      - name: Deploy to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          heroku git:remote -a digital-signature-microservice
          git push heroku main
